name: 'Issue to yaml'
description: 'Parse issue data into a yaml file'
author: LucasCalcada

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: file
  color: green

# Define your inputs here.
inputs:
  github_token:
    description: GitHub token
    default: ${{ github.token }}
    required: true
  issue_id:
    description: Github issue Id
    required: true

# Define your outputs here.
outputs:
  yamlFile:
    description: Parsed yaml file content

runs:
  using: node20
  main: dist/index.js
