on:
  issues:
    types:
      - opened

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run action
        uses: ./
        id: action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}
      - name: Get the parsed file'
        run: echo "${{ steps.action.outputs.yamlFile }}"
